server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_info?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123000
    type: com.zaxxer.hikari.HikariDataSource

langchain4j:
  openai:
    api-key: sk-58344173c5984cf787996d13160e38ec  # 替换为你的 DeepSeek API Key
    model-name: deepseek-chat      # 使用的模型名称
    base-url: https://api.deepseek.com/v1  # DeepSeek API 的 endpoint

#logging:
#  level:
#    com:
#      hac: debug
